// Acceptance checklist, end to end. Run: bash tests/make-fixtures.sh && node tests/e2e.cjs (server on :8080)
const { setup } = require('./harness.cjs');
const F = (n) => __dirname + '/fixtures/' + n; // created by tests/make-fixtures.sh
const OUT = (n) => __dirname + '/out/' + n;
let pass = 0, fail = 0;
function ok(cond, msg) { if (cond) { pass++; console.log('  ✓', msg); } else { fail++; console.log('  ✗', msg); } }
(async () => {
  const { browser, page, errors } = await setup();
  const val = (sel) => page.$eval(sel, (e) => e.value);
  const txt = (sel) => page.$eval(sel, (e) => e.textContent.trim());
  const inModal = () => page.evaluate(() => !!document.activeElement.closest('.dm'));
  const step = () => page.$eval('.prov-progress__item[aria-current="step"]', (e) => +e.dataset.step);
  const fill = async (sel, v) => { await page.fill(sel, ''); await page.type(sel, String(v)); await page.press(sel, 'Tab'); };
  const asset = (i, f) => `.asset-row:nth-child(${i}) [id$="__${f}"]`;
  const fillKeyInfo = async (o) => {
    await fill('#f-area_sqm', o.area); await fill('#f-price', o.price); await fill('#f-occupancy', o.occ); await fill('#f-rent_yearly', o.rent);
    await page.selectOption(asset(1, 'type'), o.type); await fill(asset(1, 'address'), o.address);
  };

  console.log('0. Inbox + map');
  ok((await page.$$('.deal-list .row-card')).length === 11, '11 deals listed');
  ok((await page.$$('.map-pin')).length === 11, '11 pins on the map');
  const gear = await page.$eval('[aria-label="Table settings"] svg', (e) => { const r = e.getBoundingClientRect(), b = e.closest('button').getBoundingClientRect(); return Math.abs((r.top + r.height / 2) - (b.top + b.height / 2)); });
  ok(gear < 2, `settings icon vertically centred (Δ${gear.toFixed(1)}px)`);
  await page.click('[data-map="off"]');
  ok(!(await page.isVisible('#map-panel')), 'map hidden by the switch');
  await page.click('[data-map="on"]');
  ok(await page.isVisible('#map-panel') && (await page.$$('.map-pin')).length === 11, 'map shown again with pins');
  await page.click('.map-ctl');
  ok(await page.isVisible('#map-menu'), 'pin settings dropdown opens');
  await page.click('#map-menu label:has(input[value="area"])');
  ok((await txt('.map-pin[data-id="d5"] .map-pin__label')) === '8,269 sqm', 'pins show Area');
  ok((await txt('.map-ctl__label')) === 'Area', 'dropdown button shows the chosen value');
  await page.click('#map-menu label:has([data-map-opt="showIcon"])');
  ok(!(await page.$('.map-pin .map-pin__icon')), 'industry icon hidden');
  await page.click('#map-menu label:has([data-map-opt="showLabel"])');
  ok((await page.$$eval('.map-pin', (els) => els.every((e) => e.dataset.mode === 'dot'))), 'both off → dot pins');
  await page.screenshot({ path: OUT('map-dots.png'), clip: { x: 1020, y: 230, width: 420, height: 650 } });
  await page.click('#map-menu label:has([data-map-opt="showIcon"])');
  await page.click('#map-menu label:has([data-map-opt="showLabel"])');
  await page.click('#map-menu label:has(input[value="price"])');
  await page.keyboard.press('Escape');
  ok(!(await page.isVisible('#map-menu')), 'Esc closes the dropdown');
  await page.click('.map-legend__item[data-stage="SCR"]');
  ok(!(await page.$('.map-pin[data-stage="SCR"]')), 'legend hides SCR pins');
  await page.click('.map-legend__item[data-stage="SCR"]');
  const before = await page.$eval('.map-world', (e) => e.style.transform);
  await page.click('[data-zoom="in"]');
  ok((await page.$eval('.map-world', (e) => e.style.transform)) !== before, 'zoom in changes the view');
  await page.click('[data-zoom="reset"]');
  await page.hover('.row-card[data-id="d7"]');
  ok(await page.$eval('.map-pin[data-id="d7"]', (e) => e.classList.contains('is-linked')), 'hovering a card highlights its pin');
  await page.click('.map-pin[data-id="d9"]');
  await page.waitForTimeout(200);
  ok(await page.$eval('.row-card[data-id="d9"]', (e) => e.classList.contains('is-flash')), 'clicking a pin highlights its card');

  console.log('1. Open + empty close');
  await page.click('#add-deal-btn');
  ok(await page.isVisible('.dm[role="dialog"]'), 'modal opens from New deal');
  ok(await page.evaluate(() => document.activeElement.id) === 'f-area_sqm', 'focus starts on Area');
  ok(!(await page.$('.dm [data-unit="period"]')), 'no Yearly/Monthly control in the modal');
  ok(await page.$eval('.section-heading:has(#ki-title) .units-inline', (e) => !!e.querySelector('[data-unit="area"]') && !!e.querySelector('[data-unit-select="currency"]')), 'SQM/SQF + currency sit in the Key metrics heading row');
  await page.keyboard.press('Escape');
  ok(!(await page.$('.dm')), 'Esc with no data closes silently');
  ok(await page.evaluate(() => document.activeElement.id) === 'add-deal-btn', 'focus returns to trigger');
  await page.click('#add-deal-btn');
  await page.mouse.click(10, 870);
  ok(!(await page.$('.dm')), 'overlay click with no data closes silently');
  await page.click('#add-deal-btn');
  await page.click('[data-act="close"]');
  ok(!(await page.$('.dm')), 'close icon with no data closes silently');

  console.log('2. Validation + locks');
  await page.click('#add-deal-btn');
  ok(await page.$eval('[data-step="1"]', (e) => e.getAttribute('aria-disabled')) === 'true', 'upcoming steps locked');
  await page.click('[data-act="next"]');
  ok(await step() === 0, 'Next blocked on invalid Key Info');
  ok((await page.$$('.ds-field[data-state="error"]')).length >= 6, 'required errors shown (metrics + asset type + address)');
  ok(await page.evaluate(() => document.activeElement.id) === 'f-area_sqm', 'focus moved to first invalid field');

  console.log('3. Calculations + auto fields');
  ok(!(await page.$('input#f-rent_psm')) && !(await page.$('input#f-niy')), 'auto fields are not inputs');
  ok(await page.$eval('.readonly-field[data-wrap="rent_psm"] .readonly-field__box', (e) => getComputedStyle(e).cursor) === 'default', 'auto field has default cursor');
  const bgBefore = await page.$eval('.readonly-field[data-wrap="rent_psm"] .readonly-field__box', (e) => getComputedStyle(e).backgroundColor);
  await page.hover('.readonly-field[data-wrap="rent_psm"] .readonly-field__box');
  ok(await page.$eval('.readonly-field[data-wrap="rent_psm"] .readonly-field__box', (e) => getComputedStyle(e).backgroundColor) === bgBefore, 'no hover effect on auto field');
  await fillKeyInfo({ area: 1000, price: 10000000, occ: 95, rent: 500000, type: 'Logistics', address: 'Hamngatan 12, Malmö' });
  ok(await txt('#v-rent_psm') === '500', `Rent/psm = 500 (got ${await txt('#v-rent_psm')})`);
  ok(await txt('#v-niy') === '5', `NIY = 5 (got ${await txt('#v-niy')})`);
  ok(await val('#f-price') === '10,000,000', 'price formatted on blur');
  await page.click('[data-unit="area"][data-value="sqf"]');
  ok(await val('#f-area_sqm') === '10,763.9', `area shown in sqf (got ${await val('#f-area_sqm')})`);
  ok(await txt('#l-rent_psm') === 'Rent/psf' && await txt('#v-rent_psm') === '46.45', `Rent/psf = 46.45 (got ${await txt('#v-rent_psm')})`);
  ok(await txt('#v-niy') === '5', 'NIY unchanged by the unit toggle');
  await page.click('[data-unit="area"][data-value="sqm"]');
  ok(await val('#f-area_sqm') === '1,000', 'round-trip toggle keeps the value');
  await fill('#f-rent_yearly', 600000);
  ok(await txt('#v-rent_psm') === '600' && await txt('#v-niy') === '6', 'recalculates on every input');
  await page.click('[data-act="niy-override"]');
  ok(await page.evaluate(() => document.activeElement.id) === 'f-niy', 'Override turns NIY into an input');
  await fill('#f-niy', 7.5);
  await fill('#f-rent_yearly', 800000);
  ok(await val('#f-niy') === '7.5', 'manual NIY no longer auto-updates');
  await page.click('[data-act="niy-reset"]');
  ok(await txt('#v-niy') === '8' && !(await page.$('input#f-niy')), `reset → back to auto 8 (got ${await txt('#v-niy')})`);
  await fill('#f-occupancy', 140);
  ok(await page.$eval('[data-wrap="occupancy"]', (e) => e.dataset.state) === 'error', 'occupancy > 100 rejected');
  await fill('#f-occupancy', 95);

  console.log('4. Assets (multi-asset deal)');
  await page.click('[data-act="asset-add"]');
  ok((await page.$$('.asset-row')).length === 2 && (await txt('#assets-count')) === '(2)', 'second asset added');
  ok(await page.evaluate(() => document.activeElement.id.endsWith('__type')), 'focus on the new asset type');
  await page.click('[data-act="next"]');
  ok(await step() === 0, 'empty second asset blocks Next');
  await page.selectOption(asset(2, 'type'), 'Office');
  await fill(asset(2, 'address'), 'Stortorget 3, Malmö');
  await page.click('[data-act="asset-add"]');
  await page.click('.asset-row:nth-child(3) [data-act="asset-remove"]');
  ok((await page.$$('.asset-row')).length === 2, 'asset removed');

  console.log('5. Upload');
  await page.setInputFiles('.prov-dropzone input[type=file]', [F('photo1.jpg'), F('photo2.jpg'), F('photo3.jpg'), F('huge.jpg'), F('notes.txt')]);
  ok((await page.$$('.upload-errors li')).length === 2, 'oversize + unsupported rejected and listed');
  await page.waitForSelector('.thumb[data-status="uploading"]', { state: 'detached', timeout: 10000 });
  ok(await txt('.upload-count') === '3/10', 'counter 3/10');
  await page.focus('.thumb:nth-child(2) [data-act="grip"]');
  await page.keyboard.press('ArrowLeft');
  ok(await page.$eval('.thumb:first-child img', (e) => e.alt) === 'photo2.jpg', 'keyboard reorder → photo2 is cover');
  await page.locator('.thumb:nth-child(3)').dragTo(page.locator('.thumb:nth-child(1)'), { targetPosition: { x: 5, y: 40 } });
  ok(await page.$eval('.thumb:first-child img', (e) => e.alt) === 'photo3.jpg', 'drag & drop reorder → photo3 is cover');
  await page.click('.thumb:first-child [data-act="remove"]');
  ok(await txt('.upload-count') === '2/10', 'remove works');
  await page.setInputFiles('.prov-dropzone input[type=file]', [4, 5, 6, 7, 8, 9, 10, 11, 12].map((i) => F(`photo${i}.jpg`)));
  await page.waitForSelector('.thumb[data-status="uploading"]', { state: 'detached', timeout: 10000 });
  ok(await txt('.upload-count') === '10/10' && (await page.$eval('.prov-dropzone', (e) => e.getAttribute('aria-disabled'))) === 'true', 'limit 10/10, dropzone disabled');
  await page.$eval('.dm__body', (e) => (e.scrollTop = 600));
  await page.screenshot({ path: OUT('key-info.png') });

  console.log('6. General Info');
  await page.click('[data-act="next"]');
  ok(await step() === 1, 'moved to General Info');
  ok(await page.$eval('.chip-option[data-industry="Logistics"]', (e) => e.getAttribute('aria-checked')) === 'true', 'industry prefilled from asset 1');
  await page.fill('#f-deal_name', 'Harbour Gate Logistics Park');
  await page.click('#f-location'); await page.type('#f-location', 'mal');
  await page.keyboard.press('ArrowDown'); await page.keyboard.press('Enter');
  ok(await val('#f-location') === 'Malmö, Sweden', 'location picked with keyboard');
  await page.selectOption('#f-stage', 'LOI');
  await page.click('#f-team'); await page.click('#team-opt-sc'); await page.click('#team-opt-lo');
  await page.keyboard.press('Escape');
  ok(!!(await page.$('.dm[role="dialog"]')), 'Esc in listbox did not close modal');

  console.log('7. Physical (per asset)');
  await page.click('[data-act="next"]');
  ok((await page.$$('.dm__body .form-section')).length === 2, 'one physical block per asset');
  await fill('.form-section:nth-of-type(1) [id$="__gla_sqm"]', 37380);
  await fill('.form-section:nth-of-type(1) [id$="__year_built"]', 2008);
  await fill('.form-section:nth-of-type(1) [id$="__year_renovated"]', 2000);
  ok(await page.$eval('.form-section:nth-of-type(1) [data-wrap$="__year_renovated"]', (e) => e.dataset.state) === 'error', 'renovated < built rejected');
  await fill('.form-section:nth-of-type(1) [id$="__year_renovated"]', 2019);
  await fill('.form-section:nth-of-type(2) [id$="__gla_sqm"]', 4200);
  await page.screenshot({ path: OUT('physical.png') });

  console.log('8. Financial');
  await page.click('[data-act="next"]');
  ok(!(await page.$('.dm__body [data-unit]')), 'no unit controls on Financial');
  await fill('#f-wault', 4.1);

  console.log('9. Preview');
  await page.click('[data-act="next"]');
  ok(await step() === 4, 'Preview reached');
  ok((await txt('.pv-head__sub')).endsWith('2 assets'), 'header shows 2 assets');
  ok((await page.$$('.pv-table tbody tr')).length === 2, 'assets table has 2 rows');
  await page.screenshot({ path: OUT('preview.png') });
  await page.click('[data-edit="2"]');
  ok(await step() === 2 && (await val('.form-section:nth-of-type(1) [id$="__gla_sqm"]')) === '37,380', 'Edit Assets → Physical with data');
  await page.click('[data-step="4"]');

  console.log('10. Focus trap');
  let escaped = false;
  for (let i = 0; i < 50; i++) { await page.keyboard.press('Tab'); if (!(await inModal())) escaped = true; }
  ok(!escaped, 'Tab stays inside modal');

  console.log('11. Draft');
  await page.keyboard.press('Escape');
  ok(await page.isVisible('[role="alertdialog"]'), 'dirty close asks to confirm');
  await page.click('[data-choice="draft"]');
  ok(!(await page.$('.dm')), 'Save as Draft closes');
  await page.click('#add-deal-btn');
  ok(await page.isVisible('.draft-banner'), 'draft restored');
  await page.click('[data-step="0"]');
  ok((await page.$$('.asset-row')).length === 2 && (await page.$$('.thumb')).length === 10 && (await txt('#v-niy')) === '8', 'assets, photos and NIY restored');
  await page.click('[data-act="close"]');
  await page.click('[data-choice="discard"]');
  await page.click('#add-deal-btn');
  ok((await page.$$('.asset-row')).length === 1 && (await val('#f-area_sqm')) === '', 'discard → empty form');
  await page.keyboard.press('Escape');

  console.log('12. Add Deal');
  await page.click('#add-deal-btn');
  await fillKeyInfo({ area: 8269, price: 33710000, occ: 98.5, rent: 831058, type: 'Logistics', address: 'Venlo Trade Port 1' });
  await page.click('[data-act="next"]');
  await page.fill('#f-deal_name', 'Project Gateway - Venlo Logistics');
  await page.click('[data-step="4"]');
  await page.click('[data-act="add"]');
  ok(!(await page.$('.dm')), 'modal closed');
  ok((await txt('.deal-list .row-card:first-child .row-card__name')) === 'Project Gateway - Venlo Logistics', 'new deal at top of inbox');
  ok((await page.$$('.map-pin')).length === 12 && !!(await page.$('.map-pin.is-new')), 'new deal has a pin on the map');
  await page.screenshot({ path: OUT('success.png') });

  console.log('\nconsole errors/warnings:', errors.length ? errors : 'none');
  console.log(`\n${pass} passed, ${fail} failed`);
  await browser.close();
  process.exit(fail || errors.length ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(2); });
